src/Five/AdminBundle/Form/DataMapper/GedmoTranslationMapper.php
<?php

namespace Five\AdminBundle\Form\DataMapper;

use Symfony\Component\Form\DataMapperInterface,
    Symfony\Component\Form\Exception\UnexpectedTypeException,
    Doctrine\Common\Collections\ArrayCollection;

/**
 * @author David ALLIX
 */
class GedmoTranslationMapper implements DataMapperInterface
{
    /**
     * {@inheritdoc}
     */
    public function mapDataToForms($data, $forms)
    {
        if (null === $data || array() === $data) {
            return;
        }

        if (!is_array($data) && !is_object($data)) {
            //throw new UnexpectedTypeException($data, 'object, array or empty');
        }

        foreach ($forms as $translationsFieldsForm) {
            $transName = $translationsFieldsForm->getConfig()->getName();
            $translationsFieldsConfig = $translationsFieldsForm->getConfig();
            //$translationClass = $translationsFieldsConfig->getOption('personal_translation');
            //
            $translatableClass = $translationsFieldsForm->getParent()->getConfig()->getOption( 'personal_translation' );
            $exp = explode( '_', $transName );

            //if( is_array( $exp ) )
            //{
                $locale = $exp[1];
                $transFieldName = $exp[0];            
//            $locale = $translationsFieldsForm->getConfig()->getName();

            //var_dump($transName.'// ');

            $tmpFormData = array();
            foreach ($data as $translation) {
                if ($locale === $translation->getLocale()) {
                    $tmpFormData[$translation->getField()] = $translation->getContent();
                    
                    //$translationsFieldsForm->setData( new $translatableClass( $locale, $transFieldName, $translation->getContent() ) );
                }
            }
            if(!empty( $tmpFormData ))
            {
                $translationsFieldsForm->setData($tmpFormData);
            }
            //var_dump( $tmpFormData );
            
        }
    }

    /**
     * {@inheritdoc}
     */
    public function mapFormsToData($forms, &$data)
    {
        if (null === $data) {
            return;
        }

        if (!is_array($data) && !is_object($data)) {
            throw new UnexpectedTypeException($data, 'object, array or empty');
        }

        $newData = new ArrayCollection();
        //var_dump( $forms->current()->getConfig()->getOption( 'personal_translation' ) );
        foreach ($forms as $translationsFieldsForm) {
            $translationsFieldsConfig = $translationsFieldsForm->getConfig();
            //var_dump( $translationsFieldsForm->getConfig()->getOption( 'field' ) );
            $transName = $translationsFieldsConfig->getName();
            $exp = explode( '_', $transName );

            //if( is_array( $exp ) )
            //{
                $locale = $exp[1];
                $transFieldName = $exp[0];
            //}

            //$locale = $translationsFieldsConfig->getName();
            $translatableClass = $translationsFieldsForm->getParent()->getConfig()->getOption( 'personal_translation' );
            //var_dump( '-----',$transName, $transFieldName, '-----' );
            
            $transForm = array(
                $transFieldName => $translationsFieldsForm->getData()
            );

            //print_r( $translationsFieldsForm->getData() );
///            $translationsFieldsForm
//echo  $locale;
            foreach ($transForm as $field => $content) {

                $existingTranslation = $data ? $data->filter(function($object) use ($locale, $field) {
                    return ($object && ($object->getLocale() === $locale) && ($object->getField() === $field));
                })->first() : null;

                if ($existingTranslation) {
                    $existingTranslation->setContent($content);
                    //$newData->add($existingTranslation);
                    $data[] = $existingTranslation;

                } else {
                    $translation = new $translatableClass($locale, $field, $content);
                    //var_dump( 'NEWTRANS', $content );
/*                    $translation->setLocale($locale);
                    $translation->setField($field);
                    $translation->setContent($content);*/
                    //var_dump( 'CountPRE->'.count( $data ) );
                    //$data->add($translation);
                    $data[] = $translation;
                    //var_dump( 'CountPPOST->'.count( $data ) );
                }
            }
        }
//var_dump( 'CountTransData->'.count( $data ) );
        //$data[] = $newData;
    }
}

src/Five/AdminBundle/Form/DataTransformer/JsonArrayTransformer.php
<?php

namespace Five\AdminBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class JsonArrayTransformer implements DataTransformerInterface
{
    public function transform( $json )
    {
        
    }
}

src/Five/AdminBundle/Form/DataTransformer/PictureUploadTransformer.php
<?php
namespace Five\AdminBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;
use Doctrine\Common\Persistence\ObjectManager;
use Five\AdminBundle\Entity\Picture;

class PictureUploadTransformer implements DataTransformerInterface
{
    /**
     * @var ObjectManager
     */
    private $om;

    /**
     * @param ObjectManager $om
     */
    public function __construct(ObjectManager $om)
    {
        $this->om = $om;
    }

    /**
     * Transforms an object (issue) to a string (number).
     *
     * @param  Issue|null $issue
     * @return string
     */
    public function transform($picture)
    {
        if (null === $picture) {
            return "";
        }


        return $picture;
    }

    /**
     * Transforms a string (number) to an object (issue).
     *
     * @param  string $number
     *
     * @return Issue|null
     *
     * @throws TransformationFailedException if object (issue) is not found.
     */
    public function reverseTransform($file)
    {
        if( empty($file) )
        {
            return null;
        }
/*        if (!$name) {
            return null;
        }*/

/*        $picture = $this->om
            ->getRepository('AurayCapitalSiteBundle:Picture')
            ->findOneBy(array('name' => $name))
        ;*/

/*        if (null === $picture) {
            throw new TransformationFailedException(sprintf(
                'An picture with number "%s" does not exist!',
                $picture
            ));
        }*/
        $picture = new Picture();
        $picture->setFile( $file );

        return $picture;
    }
}

src/Five/AdminBundle/Form/EventListener/AddTranslatedFieldSubscriber.php
<?php

namespace Five\AdminBundle\Form\EventListener;
/*Symfony\Component\Form\FormEvent*/
use Symfony\Component\Form\Event\DataEvent;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Form\FormError;

class AddTranslatedFieldSubscriber implements EventSubscriberInterface
{
    private $factory;
    private $options;
    private $container;

    public function __construct(FormFactoryInterface $factory, ContainerInterface $container, Array $options)
    {
        $this->factory   = $factory;
        $this->options   = $options;
        //$this->container = $container;
    }

    public static function getSubscribedEvents()
    {
        // Tells the dispatcher that we want to listen on the form.pre_set_data
        // , form.post_data and form.bind_norm_data event
        return array(
            FormEvents::PRE_SET_DATA => 'preSetData',
            FormEvents::POST_SUBMIT => 'postBind',
            FormEvents::SUBMIT => 'bindNormData'
        );
    }

    private function bindTranslations($data)
    {
        //Small helper function to extract all Personal Translation
        //from the Entity for the field we are interested in
        //and combines it with the fields

        $collection = array();
        $availableTranslations = array();

        foreach($data as $Translation)
        {
          //if( isset( $Translation->getField() ) )
          //{


//var_dump($Translation->getField());
            if(strtolower($Translation->getField()) == strtolower($this->options['field']))
            {

                $availableTranslations[ strtolower($Translation->getLocale()) ] = $Translation;
            }
          //}
        }

        foreach($this->getFieldNames() as $locale => $fieldName)
        {
            if(isset($availableTranslations[ strtolower($locale) ]))
            {
              //var_dump( 'HERE' );
                $Translation = $availableTranslations[ strtolower($locale) ];
            }
            else
            {
              //var_dump( 'HERE2' );
                $Translation = $this->createPersonalTranslation($locale, $this->options['field'], null );
            }
//var_dump( $fieldName );
            $collection[] = array(
                'locale'      => $locale,
                'fieldName'   => $fieldName,
                'translation' => $Translation,
            );
        }

        return $collection;
    }

    private function getFieldNames()
    {
        //helper function to generate all field names in format:
        // '<locale>' => '<field>|<locale>'
        $collection = array();

        foreach($this->options['locales'] as $locale)
        {
            $collection[ $locale ] = $this->options['field'] ."_". $locale;
          //var_dump( $this->options['field'] );
            //.":". $locale;
        }

        return $collection;
    }

    private function createPersonalTranslation($locale, $field, $content)
    {
        //creates a new Personal Translation
        $className = $this->options['personal_translation'];
        //$expl = explode( ':', $locale );
        //$locale = ( count( $expl ) > 1 ? $expl[ 1 ] : $locale );
        if( is_array( $content ) )
        {
          var_dump( $content );
        }
        $Translation = new $className($locale, $field, $content);
/*        $Translation->setLocale($locale);
        $Translation->setField($field);
        $Translation->setContent($content);*/

        return $Translation;
    }

    public function bindNormData(FormEvent $event)
    {
        //Validates the submitted form
        $data = $event->getData();
        $form = $event->getForm();
//var_dump($form);
       // $validator = $this->container->get('validator');

        foreach($this->getFieldNames() as $locale => $fieldName)
        {
            $content = $form->get($fieldName)->getData();

            if(
                NULL === $content &&
                in_array($locale, $this->options['required_locale']))
            {
                //$form->addError(new FormError(sprintf("Field '%s' for locale '%s' cannot be blank", $this->options['field'], $locale)));
            }
            else
            {
                $Translation = $this->createPersonalTranslation($locale, $fieldName, $content);
               // $errors = $validator->validate($Translation, array(sprintf("%s:%s", $this->options['field'], $locale)));

/*                if(count($errors) > 0)
                {
                    foreach($errors as $error)
                    {
                        $form->addError(new FormError($error->getMessage()));
                    }
                }*/
            }
        }
    }

    public function postBind(FormEvent $event)
    {
       //if the form passed the validattion then set the corresponding Personal Translations
       $form = $event->getForm();
       $data = $form->getData();

       $entity = $form->getParent()->getData();

       foreach($this->bindTranslations($data) as $binded)
       {
           $content = $form->get($binded['fieldName'])->getData();
           $Translation = $binded['translation'];

           // set the submitted content
           $Translation->setContent($content);

           //test if its new
           if($Translation->getId())
           {
               //Delete the Personal Translation if its empty
               if(
                   NULL === $content &&
                   $this->options['remove_empty']
               )
               {
                   $data->removeElement($Translation);

                   if($this->options['entity_manager_removal'])
                   {
                       //$this->container->get('doctrine.orm.entity_manager')->remove($Translation);
                   }
               }
           }
           elseif(NULL !== $content)
           {
               //add it to entity
               $entity->addTranslation($Translation);

               if(! $data->contains($Translation))
               {
                   $data->add($Translation);
               }
           }
       }
    }

    public function preSetData2(FormEvent $event)
    {
        $form = $event->getForm();

        $translatableClass = $form->getParent()->getConfig()->getDataClass();

        $formOptions = $form->getConfig()->getOptions();
        $childrenOptions = $this->translationForm->getChildrenOptions($translatableClass, $formOptions);

        foreach ($formOptions['locales'] as $locale) {
            if (isset($childrenOptions[$locale])) {
                $form->add($locale, 'a2lix_translationsFields', array(
                    'fields' => $childrenOptions[$locale],
                    'translation_class' => $this->translationForm->getTranslationClass($translatableClass),
                ));
            }
        }
    }      


    public function preSetData(FormEvent $event)
    {
        //Builds the custom 'form' based on the provided locales
        $data = $event->getData();
        $form = $event->getForm();
        

        $translatableClass = $form->getConfig()->getOption( 'personal_translation' );
        //var_dump($translatableClass);
        // During form creation setData() is called with null as an argument
        // by the FormBuilder constructor. We're only concerned with when
        // setData is called with an actual Entity object in it (whether new,
        // or fetched with Doctrine). This if statement let's us skip right
        // over the null condition.
        if (null === $data)
        {
            return;
        }
//var_dump( $this->options['widget'] );
        foreach($this->bindTranslations($data) as $binded)
        {          /*var_dump( $this->options['widget'] );*/
      //var_dump($binded['translation'],$binded['translation']->getContent());
          //var_dump(str_replace( ':'.$binded['locale'], '', $binded['translation']->getField() ));
            $form->add( $this->factory->createNamed( $binded['fieldName'], $this->options['widget'], $binded['translation']->getContent(), array(
              'label'         => $this->options[ 'field_label' ],
              'required'      => in_array($binded['locale'], $this->options['required_locale']),
              //'mapped'        => false,
              'attr'          => $this->options['attr'],
              'auto_initialize' => false,
              //'data_class' => $translatableClass
            )) );
        }
    }
}

src/Five/AdminBundle/Form/Type/ArrayCollectionType.php
<?php
namespace Five\AdminBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ArrayCollectionType extends AbstractType
{
    private $genderChoices;

    public function __construct( array $genderChoices = array() )
    {
        $this->genderChoices = $genderChoices;

    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $collection = array(
            'type'            => 'text',
            'allow_add'       => true,
            'allow_delete'    => true,
            'prototype'       => true,
            'sub_widget_col'  => 10,
            'button_col'      => 2,
            'prototype_name'  => 'inlinep',
            'add_button_text' => 'Add'  
        );

        foreach( $this->genderChoices as $key => $value )
         {
            $config = array(
                "label"        => false,
                'attr' => array(
                    'placeholder' => ucfirst( $key ),
                    'simple_col'  => 6
                )
            );            
            $configs = ( $value == '1bootstrap_collection' ) ? array_merge( $config, $collection ) : $config;
            //var_dump($configs);
            $builder->add( $builder->create( $key, $value, $configs ) );

/*            $builder->add( 
                $builder->create( $key, $value, array(
                
                    "label"        => false,
                    'attr' => array(
                        'placeholder' => ucfirst( $key ),
                        'simple_col'  => 6
                    )
                ) )
            );*/
         }
    }

    public function setDefaultOptions( OptionsResolverInterface $resolver )
    {
        $resolver->setDefaults( array(
            'required'     => false,
            'by_reference' => false,
            //'compound'     => true,
                    'attr' => array(

                        'style' => 'horizontal'
                        
                    )
        ) );
    }

    public function getParent()
    {
        return 'collection';
    }

    public function getName()
    {
        return 'array_collection';
    }
}

src/Five/AdminBundle/Resources/views/Form/bootstrap-horizontal.html.twig
{% block form_start %}
{% spaceless %}
    {% set method = method|upper %}
    {% if method in ["GET", "POST"] %}
        {% set form_method = method %}
    {% else %}
        {% set form_method = "POST" %}
    {% endif %}
    <form method="{{ form_method|lower }}" class="form-horizontal" 
         action="{{ action }}"{% for attrname, attrvalue in attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}{% if multipart %} enctype="multipart/form-data"{% endif %}>
    {% if form_method != method %}
        <input type="hidden" name="_method" value="{{ method }}" />
    {% endif %}
{% endspaceless %}
{% endblock form_start %}

{% block form_row %}
{% spaceless %}
    <div class="control-group">
        {{ form_label(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
    </div>
{% endspaceless %}
{% endblock form_row %}

src/Five/AdminBundle/Resources/views/Form/bootstrap.html.twig
{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
    <ul class="alert alert-error">
        {% for error in errors %}
            <li>{{ error.message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}
    
{% block button_attributes %}
{% spaceless %}
    id="{{ id }}" name="{{ full_name }}"{% if disabled %} disabled="disabled"{% endif %}
    {% set hasClass = false %}
    {% for attrname, attrvalue in attr %}
        {{ attrname }}="{{ attrvalue }}"
        {% if attrname == "class" %}
          {% set hasClass = true %}
        {% endif %}
    {% endfor %}
    {% if not hasClass %}
    class="btn"
    {% endif %}
{% endspaceless %}
{% endblock button_attributes %}

src/Five/AdminBundle/Resources/views/Form/collectionArray.html.twig
{% extends 'FiveAdminBundle:Helpers:five-box.html.twig' %}

{# {% form_theme form _self %}

{% block form_row %}
{% spaceless %}
    {% set type = type|default('text') %}

    {% if type == 'hidden' %}
 
        {{ block( 'hidden_widget' ) }}
    {% else %}

        <div class="form-group col-md-6">
            
            {{ form_label( form ) }}
            <div class="input-group">
                <div class="input-group-addon">
                    <i class="fa fa-list-ol"></i>
                </div>
                {{ form_widget(form, { attr : { class : 'form-control'  } }) }}
                <div>{{ form_errors(form) }}</div>
            </div><!-- /.input group -->
        </div>
    {% endif %}
{% endspaceless %}
{% endblock form_row %} #}

{% block boxBody %}

    <div class="{{ class }}" id="{{ id is defined ? id : '' }}" data-prototype="{{ form_widget( boxPrototype )| e }}">
        {# {{ form.procedures | length }} #}
        {% block boxForm %}
        {% endblock %}
        {{form_widget(entities)}}
        {% for entity in entities %}
            {# {{ form_row( entity ) }} #}
            {# {{ form_widget( procedure.procedure ) }} #}
{#                     <div class="form-group">

                        {{ form_label( procedure ) }}
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-phone"></i>
                            </div>
                            {{ form_widget(procedure, { attr : { class : 'form-control'  } }) }}                            
                        </div><!-- /.input group -->
                    </div>        
                    <div class="{{ colClass }}">
                        <div class="input-group">
                            {{ form_row(procedure) }}
                        </div>
                    </div> #}
        {% endfor %}            
    </div>      
{% endblock %}

src/Five/AdminBundle/Resources/views/Form/fields.html.twig
{% block gender_widget %}
    {% spaceless %}
        {% if expanded %}
            <ul {{ block('widget_container_attributes') }}>
            {% for child in form %}
                <li>
                    {{ form_widget(child) }}
                    {{ form_label(child) }}
                </li>
            {% endfor %}
            </ul>
        {% else %}
            {# just let the choice widget render the select tag #}
            {{ block('choice_widget') }}
        {% endif %}
    {% endspaceless %}
{% endblock %}

{% block form_row %}
{% spaceless %}
    {% set type = type|default('text') %}

    {% if type == 'hidden' %}
 
        {{ block( 'hidden_widget' ) }}
    {% else %}

        {{ form_label(form) }}
        <div class="form-group">
            {{ form_errors(form) }}
            {{ form_widget(form, { attr : { class : 'form-control' } }) }}
        </div> 
    
    {% endif %}
{% endspaceless %}
{% endblock form_row %}

{% block form_widget_simple %}
{% spaceless %}
    {% set type = type|default('text') %}

    {% if type == 'hidden' %}
        {% if name == 'testData' %}
            {% set data = value | raw | json_encode() %}
            {{ data | raw }}
            {% for row in data %}
                {% for key,val in row %}
                {{ key }} : {{ val }}<br />
                {% endfor %}
            {% endfor %}
        {% endif %}
        <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
    {% else %}    
        {% set classType = {
                'email' : 'fa-envelope',
                'telephone' : 'fa-phone'
            } 
        %}
        <div class="input-group">
            <span class="input-group-addon"><i class="fa {{ name == 'email' or name == 'telephone' ? classType[ name ] : 'fa-edit'}}"></i></span>
            <input type="{{ type }}" class="form-control" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
        </div>
    {% endif %}
    
{% endspaceless %}
{% endblock form_widget_simple %}

{% block choice_widget_collapsed %}
{% spaceless %}
    {% if required and empty_value is none and not empty_value_in_choices and not multiple %}
        {% set required = false %}
    {% endif %}
    
    {% if id in [ 'date_of_birth_year', 'date_of_birth_month', 'date_of_birth_day' ] %}

    <div class="col-lg-4">

    {% endif %}

    <select class="form-control" {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %}>
        {% if empty_value is not none %}
            <option value=""{% if required and value is empty %} selected="selected"{% endif %}>{{ empty_value|trans({}, translation_domain) }}</option>
        {% endif %}
        {% if preferred_choices|length > 0 %}
            {% set options = preferred_choices %}
            {{ block('choice_widget_options') }}
            {% if choices|length > 0 and separator is not none %}
                <option disabled="disabled">{{ separator }}</option>
            {% endif %}
        {% endif %}
        {% set options = choices %}
        {{ block('choice_widget_options') }}
    </select>

    {% if id in [ 'date_of_birth_year', 'date_of_birth_month', 'date_of_birth_day' ] %}

    </div>

    {% endif %}    
{% endspaceless %}
{% endblock choice_widget_collapsed %}

{% block textarea_widget %}
    {% if attr.class is defined %}
        {# {% set attr.class = attr.class ~ ( ' form-control' ) %} #}

    {% endif %}
    <textarea class="form-control" {{ block('widget_attributes') }}>{{ value }}</textarea>
{% endblock textarea_widget %}

src/Five/AdminBundle/Resources/views/Form/fields2.html.twig
{# FORM RENDERING FOR BOOTSTRAP 3 AND ANGULAR INTEGRATION #}

{% extends 'form_div_layout.html.twig' %}

{% block form_row %}
{#                 {% for key,val in form.vars.block_prefixes %}
                {{ key }} -> {{ val }}<br/>
                {% endfor %} #}
    {% set formName = _self.getTopFormName(form) %}
    {% set modelName = form.vars.full_name | replace({'[' : '.', ']' : ''}) %}
    {% set formModelName = formName ~ "['" ~ form.vars.full_name ~ "']" %}
    {% set ngClass = "ng-class=\"{ 'has-error': " ~ formModelName ~ ".$invalid && !" ~ formModelName ~ ".$pristine }\"" %}

    {# possible form types are 'basic', 'horizontal' and 'inline' #}
    {# other types are not implemented yet #}
    {% set formType = 'basic' %}


    {% if "checkbox" in form.vars.block_prefixes or "radio" in form.vars.block_prefixes or
        ("choice" in form.vars.block_prefixes and "expanded" in form.vars and form.vars.expanded == true)
    %}
        {# {% set attr = attr | merge({ 'ng-model': modelName }) %} #}
    {% else %}
        {% set classNames = 'form-control' %}
        {% set class = 'class' in attr | keys ? attr.class ~ ' ' ~ classNames : classNames %}
        {% set attr = attr | merge({ 'class': class }) %}
    {% endif %}


    {% if "checkbox" in form.vars.block_prefixes or "radio" in form.vars.block_prefixes %}

        <div class="checkbox">
            <label>
                {{ form_widget(form, { 'attr': attr }) }}
                {{ form.vars.label | default(form.vars.name | humanize) }}
            </label>
        </div>

    {% elseif "choice" in form.vars.block_prefixes %}

        <div class="form-group" {# {{ ngClass | raw }} #}>
            {{ form_label(form, null) }}

            {% if "expanded" in form.vars and form.vars.expanded == true %}
                {% for index, choice in form %}
                    {% if index ~'' != 'placeholder' %}
                        <div class="radio">
                            <label>
                                {{ form_widget(choice, { 'attr': attr }) }}
                                {{ choice.vars.label }}
                            </label>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                {{ form_widget(form, { 'attr': attr }) }}
                {# <span class="help-block" ng-show="{{ formModelName }}.$error.invalid">Please choose a valid option</span> #}
            {% endif %}
        </div>

    {% else %}

        <div class="form-group"{#  {{ ngClass | raw }} #}>
            {{ form_label(form, null) }}
            {{ form_widget(form, { 'attr': attr }) }}
            {# <span class="help-block" ng-show="{{ formModelName }}.$error.invalid">Please choose a valid option</span> #}
        </div>

    {% endif %}
{% endblock form_row %}


{% block hidden_row %}

    {% if form.vars.name == '_token' %}
        {% set modelName = _self.getTopFormName(form) ~'._token' %}
        {% set attr = attr | merge({ 'ng-model': modelName, 'ng-init': modelName ~' = "' ~ form.vars.data ~ '"' }) %}
    {% else %}
        {% set modelName = form.vars.full_name | replace({'[' : '.', ']' : ''}) %}
        {% set attr = attr | merge({ 'ng-model': modelName }) %}
    {% endif %}


    {{ form_widget(form, { 'attr': attr }) }}
{% endblock hidden_row %}



{% macro getTopFormName(form) %}{% spaceless %}

    {% if not form.parent is null %}
        {{ _self.getTopFormName(form.parent) }}
    {% elseif 'attr' in form.vars | keys and 'name' in form.vars.attr | keys %}
        {{ form.vars.attr.name }}
    {% else %}
        {{ form.vars.name }}
    {% endif %}

{% endspaceless %}{% endmacro %}